language: node_js
node_js:
  - "10"
dist: trusty
sudo: true

branches:
  only:
    - master

cache:
  directories:
    - node_modules

install:
  - npm install -g yarn

script:
  - npm run e2e
  - yarn build --base-href https://devstr-web-app.herokuapp.com
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master

notifications:
  email:
    recipients:
      - gr2devstr@gmail.com
    on_success: always
    on_failure: always
